### ISSUE TITLE
What is the format of the server URL filled in

### ISSUE THREAD

**Issue by mushroom11s** [ls1intum/bamboo-server-notification-plugin#22]
Hello,
I have some question.I want to use this plugin, but I don't know what configuration to fill in.

- The format of the server URL is as follows? 
http://ip:port/api/apps/private/appid/userid/webhook 

- And SERVER_PLUGIN_SECRET_PASSWORD value is X-Auth-Token in request header?
- How to config channel want send?I I does't find it.
- I was add log level in bamboo,but it dost print the log. 
![image](https://user-images.githubusercontent.com/28756933/132710417-6465b610-8eb2-4c20-aff3-3eccfa5df9c0.png)

TFYH

**Comment by mushroom11s** [comment]
@sleiss help :(

**Comment by sleiss** [comment]
Hey @mushroom11s 

- The format of the server URL looks fine.
- I believe that the `SERVER_PLUGIN_SECRET_PASSWORD` is currently not set as `X-Auth-Token` in the request header but instead it is only present within the JSON Payload
- I don't quite get your question, which channel are you referring to?
- We are mostly using the chain log (https://github.com/ls1intum/bamboo-server-notification-plugin#debug), I'm not really familiar with the way the bamboo loglevels work, sorry.

**Comment by mushroom11s** [comment]
- I mean should I get the value of SERVER_PLUGIN_SECRET_PASSWORD in the rocket chat request header of   X-Auth-Token  properties？
- to whom do it send notification messages by default,I want to send it to the channel specified in rocket.chat.

**Comment by sleiss** [comment]
@mushroom11s This plugin can send requests to any URL but is not designed in a special way to work with RocketChat.
However, there is a fork of this plugin by RocketChat: https://github.com/RocketChat/bamboo-server-notification-plugin
I believe that they offer the features you require, so you should probably check that out.

**Comment by mushroom11s** [comment]
😅I thought it was only for bamboo. Thank you, have a good day
